// Package unboundapiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package unboundapiclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// ServerUrlTheProductionAPIServerHostVariable is the `host` variable for ServerUrlTheProductionAPIServer
type ServerUrlTheProductionAPIServerHostVariable string

// ServerUrlTheProductionAPIServerHostVariableDefault is the default value for the `host` variable for ServerUrlTheProductionAPIServer
const ServerUrlTheProductionAPIServerHostVariableDefault = "http://127.0.0.1:8080"

// NewServerUrlTheProductionAPIServer constructs the Server URL for The production API server, with the provided variables.
func NewServerUrlTheProductionAPIServer(host ServerUrlTheProductionAPIServerHostVariable) (string, error) {
	u := "{host}"

	u = strings.ReplaceAll(u, "{host}", string(host))

	if strings.Contains(u, "{") || strings.Contains(u, "}") {
		return "", fmt.Errorf("after mapping variables, there were still `{` or `}` characters in the string: %#v", u)
	}

	return u, nil
}

// PostConfigClauseAttributeValueIdJSONBody defines parameters for PostConfigClauseAttributeValueId.
type PostConfigClauseAttributeValueIdJSONBody struct {
	Value *string `json:"value,omitempty"`
}

// PutConfigClauseAttributeValueIdJSONBody defines parameters for PutConfigClauseAttributeValueId.
type PutConfigClauseAttributeValueIdJSONBody struct {
	Value *string `json:"value,omitempty"`
}

// PostConfigClauseAttributeValueIdJSONRequestBody defines body for PostConfigClauseAttributeValueId for application/json ContentType.
type PostConfigClauseAttributeValueIdJSONRequestBody PostConfigClauseAttributeValueIdJSONBody

// PutConfigClauseAttributeValueIdJSONRequestBody defines body for PutConfigClauseAttributeValueId for application/json ContentType.
type PutConfigClauseAttributeValueIdJSONRequestBody PutConfigClauseAttributeValueIdJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// DeleteConfigClauseAttributeValueId request
	DeleteConfigClauseAttributeValueId(ctx context.Context, clause string, attribute string, valueId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetConfigClauseAttributeValueId request
	GetConfigClauseAttributeValueId(ctx context.Context, clause string, attribute string, valueId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostConfigClauseAttributeValueIdWithBody request with any body
	PostConfigClauseAttributeValueIdWithBody(ctx context.Context, clause string, attribute string, valueId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostConfigClauseAttributeValueId(ctx context.Context, clause string, attribute string, valueId string, body PostConfigClauseAttributeValueIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutConfigClauseAttributeValueIdWithBody request with any body
	PutConfigClauseAttributeValueIdWithBody(ctx context.Context, clause string, attribute string, valueId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutConfigClauseAttributeValueId(ctx context.Context, clause string, attribute string, valueId string, body PutConfigClauseAttributeValueIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) DeleteConfigClauseAttributeValueId(ctx context.Context, clause string, attribute string, valueId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteConfigClauseAttributeValueIdRequest(c.Server, clause, attribute, valueId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetConfigClauseAttributeValueId(ctx context.Context, clause string, attribute string, valueId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConfigClauseAttributeValueIdRequest(c.Server, clause, attribute, valueId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostConfigClauseAttributeValueIdWithBody(ctx context.Context, clause string, attribute string, valueId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostConfigClauseAttributeValueIdRequestWithBody(c.Server, clause, attribute, valueId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostConfigClauseAttributeValueId(ctx context.Context, clause string, attribute string, valueId string, body PostConfigClauseAttributeValueIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostConfigClauseAttributeValueIdRequest(c.Server, clause, attribute, valueId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutConfigClauseAttributeValueIdWithBody(ctx context.Context, clause string, attribute string, valueId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutConfigClauseAttributeValueIdRequestWithBody(c.Server, clause, attribute, valueId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutConfigClauseAttributeValueId(ctx context.Context, clause string, attribute string, valueId string, body PutConfigClauseAttributeValueIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutConfigClauseAttributeValueIdRequest(c.Server, clause, attribute, valueId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDeleteConfigClauseAttributeValueIdRequest generates requests for DeleteConfigClauseAttributeValueId
func NewDeleteConfigClauseAttributeValueIdRequest(server string, clause string, attribute string, valueId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clause", runtime.ParamLocationPath, clause)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "attribute", runtime.ParamLocationPath, attribute)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "value_id", runtime.ParamLocationPath, valueId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/config/%s/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetConfigClauseAttributeValueIdRequest generates requests for GetConfigClauseAttributeValueId
func NewGetConfigClauseAttributeValueIdRequest(server string, clause string, attribute string, valueId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clause", runtime.ParamLocationPath, clause)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "attribute", runtime.ParamLocationPath, attribute)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "value_id", runtime.ParamLocationPath, valueId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/config/%s/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostConfigClauseAttributeValueIdRequest calls the generic PostConfigClauseAttributeValueId builder with application/json body
func NewPostConfigClauseAttributeValueIdRequest(server string, clause string, attribute string, valueId string, body PostConfigClauseAttributeValueIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostConfigClauseAttributeValueIdRequestWithBody(server, clause, attribute, valueId, "application/json", bodyReader)
}

// NewPostConfigClauseAttributeValueIdRequestWithBody generates requests for PostConfigClauseAttributeValueId with any type of body
func NewPostConfigClauseAttributeValueIdRequestWithBody(server string, clause string, attribute string, valueId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clause", runtime.ParamLocationPath, clause)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "attribute", runtime.ParamLocationPath, attribute)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "value_id", runtime.ParamLocationPath, valueId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/config/%s/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutConfigClauseAttributeValueIdRequest calls the generic PutConfigClauseAttributeValueId builder with application/json body
func NewPutConfigClauseAttributeValueIdRequest(server string, clause string, attribute string, valueId string, body PutConfigClauseAttributeValueIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutConfigClauseAttributeValueIdRequestWithBody(server, clause, attribute, valueId, "application/json", bodyReader)
}

// NewPutConfigClauseAttributeValueIdRequestWithBody generates requests for PutConfigClauseAttributeValueId with any type of body
func NewPutConfigClauseAttributeValueIdRequestWithBody(server string, clause string, attribute string, valueId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clause", runtime.ParamLocationPath, clause)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "attribute", runtime.ParamLocationPath, attribute)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "value_id", runtime.ParamLocationPath, valueId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/config/%s/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DeleteConfigClauseAttributeValueIdWithResponse request
	DeleteConfigClauseAttributeValueIdWithResponse(ctx context.Context, clause string, attribute string, valueId string, reqEditors ...RequestEditorFn) (*DeleteConfigClauseAttributeValueIdResponse, error)

	// GetConfigClauseAttributeValueIdWithResponse request
	GetConfigClauseAttributeValueIdWithResponse(ctx context.Context, clause string, attribute string, valueId string, reqEditors ...RequestEditorFn) (*GetConfigClauseAttributeValueIdResponse, error)

	// PostConfigClauseAttributeValueIdWithBodyWithResponse request with any body
	PostConfigClauseAttributeValueIdWithBodyWithResponse(ctx context.Context, clause string, attribute string, valueId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostConfigClauseAttributeValueIdResponse, error)

	PostConfigClauseAttributeValueIdWithResponse(ctx context.Context, clause string, attribute string, valueId string, body PostConfigClauseAttributeValueIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PostConfigClauseAttributeValueIdResponse, error)

	// PutConfigClauseAttributeValueIdWithBodyWithResponse request with any body
	PutConfigClauseAttributeValueIdWithBodyWithResponse(ctx context.Context, clause string, attribute string, valueId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutConfigClauseAttributeValueIdResponse, error)

	PutConfigClauseAttributeValueIdWithResponse(ctx context.Context, clause string, attribute string, valueId string, body PutConfigClauseAttributeValueIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutConfigClauseAttributeValueIdResponse, error)
}

type DeleteConfigClauseAttributeValueIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Items  *map[string]interface{} `json:"items,omitempty"`
		Status *int                    `json:"status,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r DeleteConfigClauseAttributeValueIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteConfigClauseAttributeValueIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetConfigClauseAttributeValueIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Items  *map[string]interface{} `json:"items,omitempty"`
		Status *int                    `json:"status,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetConfigClauseAttributeValueIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConfigClauseAttributeValueIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostConfigClauseAttributeValueIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		Items  *map[string]interface{} `json:"items,omitempty"`
		Status *int                    `json:"status,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostConfigClauseAttributeValueIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostConfigClauseAttributeValueIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutConfigClauseAttributeValueIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Items  *map[string]interface{} `json:"items,omitempty"`
		Status *int                    `json:"status,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PutConfigClauseAttributeValueIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutConfigClauseAttributeValueIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// DeleteConfigClauseAttributeValueIdWithResponse request returning *DeleteConfigClauseAttributeValueIdResponse
func (c *ClientWithResponses) DeleteConfigClauseAttributeValueIdWithResponse(ctx context.Context, clause string, attribute string, valueId string, reqEditors ...RequestEditorFn) (*DeleteConfigClauseAttributeValueIdResponse, error) {
	rsp, err := c.DeleteConfigClauseAttributeValueId(ctx, clause, attribute, valueId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteConfigClauseAttributeValueIdResponse(rsp)
}

// GetConfigClauseAttributeValueIdWithResponse request returning *GetConfigClauseAttributeValueIdResponse
func (c *ClientWithResponses) GetConfigClauseAttributeValueIdWithResponse(ctx context.Context, clause string, attribute string, valueId string, reqEditors ...RequestEditorFn) (*GetConfigClauseAttributeValueIdResponse, error) {
	rsp, err := c.GetConfigClauseAttributeValueId(ctx, clause, attribute, valueId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConfigClauseAttributeValueIdResponse(rsp)
}

// PostConfigClauseAttributeValueIdWithBodyWithResponse request with arbitrary body returning *PostConfigClauseAttributeValueIdResponse
func (c *ClientWithResponses) PostConfigClauseAttributeValueIdWithBodyWithResponse(ctx context.Context, clause string, attribute string, valueId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostConfigClauseAttributeValueIdResponse, error) {
	rsp, err := c.PostConfigClauseAttributeValueIdWithBody(ctx, clause, attribute, valueId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostConfigClauseAttributeValueIdResponse(rsp)
}

func (c *ClientWithResponses) PostConfigClauseAttributeValueIdWithResponse(ctx context.Context, clause string, attribute string, valueId string, body PostConfigClauseAttributeValueIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PostConfigClauseAttributeValueIdResponse, error) {
	rsp, err := c.PostConfigClauseAttributeValueId(ctx, clause, attribute, valueId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostConfigClauseAttributeValueIdResponse(rsp)
}

// PutConfigClauseAttributeValueIdWithBodyWithResponse request with arbitrary body returning *PutConfigClauseAttributeValueIdResponse
func (c *ClientWithResponses) PutConfigClauseAttributeValueIdWithBodyWithResponse(ctx context.Context, clause string, attribute string, valueId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutConfigClauseAttributeValueIdResponse, error) {
	rsp, err := c.PutConfigClauseAttributeValueIdWithBody(ctx, clause, attribute, valueId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutConfigClauseAttributeValueIdResponse(rsp)
}

func (c *ClientWithResponses) PutConfigClauseAttributeValueIdWithResponse(ctx context.Context, clause string, attribute string, valueId string, body PutConfigClauseAttributeValueIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutConfigClauseAttributeValueIdResponse, error) {
	rsp, err := c.PutConfigClauseAttributeValueId(ctx, clause, attribute, valueId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutConfigClauseAttributeValueIdResponse(rsp)
}

// ParseDeleteConfigClauseAttributeValueIdResponse parses an HTTP response from a DeleteConfigClauseAttributeValueIdWithResponse call
func ParseDeleteConfigClauseAttributeValueIdResponse(rsp *http.Response) (*DeleteConfigClauseAttributeValueIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteConfigClauseAttributeValueIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Items  *map[string]interface{} `json:"items,omitempty"`
			Status *int                    `json:"status,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetConfigClauseAttributeValueIdResponse parses an HTTP response from a GetConfigClauseAttributeValueIdWithResponse call
func ParseGetConfigClauseAttributeValueIdResponse(rsp *http.Response) (*GetConfigClauseAttributeValueIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConfigClauseAttributeValueIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Items  *map[string]interface{} `json:"items,omitempty"`
			Status *int                    `json:"status,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostConfigClauseAttributeValueIdResponse parses an HTTP response from a PostConfigClauseAttributeValueIdWithResponse call
func ParsePostConfigClauseAttributeValueIdResponse(rsp *http.Response) (*PostConfigClauseAttributeValueIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostConfigClauseAttributeValueIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			Items  *map[string]interface{} `json:"items,omitempty"`
			Status *int                    `json:"status,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParsePutConfigClauseAttributeValueIdResponse parses an HTTP response from a PutConfigClauseAttributeValueIdWithResponse call
func ParsePutConfigClauseAttributeValueIdResponse(rsp *http.Response) (*PutConfigClauseAttributeValueIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutConfigClauseAttributeValueIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Items  *map[string]interface{} `json:"items,omitempty"`
			Status *int                    `json:"status,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
